// <auto-generated />
using System;
using InternetShopWebApp.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternetShopWebApp.Migrations
{
    [DbContext(typeof(ShopContext))]
    partial class ShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InternetShopWebApp.Models.CathegoryModel", b =>
                {
                    b.Property<int>("Cathegory_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cathegory_ID"));

                    b.Property<string>("Cathegory_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Parent_ID")
                        .HasColumnType("int");

                    b.HasKey("Cathegory_ID");

                    b.ToTable("Cathegory");
                });

            modelBuilder.Entity("InternetShopWebApp.Models.OrderItemModel", b =>
                {
                    b.Property<int>("Order_Item_Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Order_Item_Code"));

                    b.Property<int?>("Amount_Order_Item")
                        .HasColumnType("int");

                    b.Property<int?>("Order_Code")
                        .HasColumnType("int");

                    b.Property<int?>("Order_Sum")
                        .HasColumnType("int");

                    b.Property<int?>("Product_Code")
                        .HasColumnType("int");

                    b.Property<int>("Status_Order_Item_Table_ID")
                        .HasColumnType("int");

                    b.HasKey("Order_Item_Code");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("InternetShopWebApp.Models.ProductModel", b =>
                {
                    b.Property<int>("Product_Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Product_Code"));

                    b.Property<float>("BestBeforeDate")
                        .HasColumnType("real");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfManufacture")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MarketPrice")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberInStock")
                        .HasColumnType("int");

                    b.Property<int>("OrderItem_Code")
                        .HasColumnType("int");

                    b.Property<int>("PurchasePrice")
                        .HasColumnType("int");

                    b.HasKey("Product_Code");

                    b.HasIndex("OrderItem_Code");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("InternetShopWebApp.Models.ProductModel", b =>
                {
                    b.HasOne("InternetShopWebApp.Models.OrderItemModel", "ProductOrderItem")
                        .WithMany("Products")
                        .HasForeignKey("OrderItem_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductOrderItem");
                });

            modelBuilder.Entity("InternetShopWebApp.Models.OrderItemModel", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
